baseURL = 'https://j6e.github.io/'
languageCode = 'en-us'
title = 'Joan Garcia Esquerdo'
theme = "yinyang"
enableRobotsTXT = true
pygmentsUseClasses = true

[author]
  email = "joan.g.esquerdo[at]gmail.com"
  name = "Joan Garcia Esquerdo"

[params]
  headTitle = "J6E - Joan G. Esquerdo ğŸ»ğŸ‘¨ğŸ»â€ğŸ’»"
  mainSections = ["blog"]
  favicon = "img/favicon.ico"
  description = "Joan G. Esquerdo's blog"

[[params.socials]]
name = "Bio"
link = "/bio/"
[[params.socials]]
name = "Github"
link = "https://github.com/j6e"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2